server:
  port: 8084
spring:
  application:
    name: zipkin-service
 # zipkin:
  #  base-url: http://127.0.0.1:9411/
 # sleuth:
  #  sampler:
   #   probability: 1.0
#sample:
 # zipkin:
    # When enabled=false, traces log to the console. Comment to send to zipkin
  #  enabled: false
